### ISSUE TITLE
Save mappings between power cycles (and allow reset)

### ISSUE THREAD

**Issue by zachberry** [bagofarms/midi-channel-mapper#6]
If we can I'd like to save the mappings to EEPROM. Then, maybe holding the save button for 5 seconds or something could reset the mappings to default.

**Comment by bagofarms** [comment]
This should help:  https://www.arduino.cc/en/Reference/EEPROM

**Comment by bagofarms** [comment]
Still need to implement a reset system.

**Comment by bagofarms** [comment]
Resetting is now allowed by holding down the save button while resetting
